### ISSUE TITLE
No longer compatible with beta@8

### ISSUE THREAD

**Issue by salamwaddah** [abbasudo/pulse-users#1]
Abbasudo\PulseUsers\Livewire\PulseUsers::graph(string $type, string $aggregate): Illuminate\Support\Collection must be compatible with Laravel\Pulse\Livewire\Card::graph(array $types, string $aggregate): Illuminate\Support\Collection

**Comment by rhurling** [comment]
@abbasudo Could you do a new release with this fix?

**Comment by abbasudo** [comment]
@rhurling done [v0.3.0](https://github.com/abbasudo/pulse-users/releases/tag/v0.3.0)
