### ISSUE TITLE
Seems to only be showing a few hours

### ISSUE THREAD

**Issue by tobya** [abbasudo/pulse-users#5]
Hi

I installed the plugin and it is working but only seems to show the last 2 or 3 hours of stats.  I have set time to hour, 6 hours, 24 hours all to no avail.

I've only been running it for about 12 hours so far.

Any ideas what might be the issue?

**Comment by ziming** [comment]
i observed that too. but not sure what is the bug causing it

**Comment by dmitry-buzzwoo** [comment]
There is a problem in the query, the period can be ignored here.
<img width="641" alt="Screenshot 2024-10-30 at 22 20 52" src="https://github.com/user-attachments/assets/fd2cb7e7-c034-4e36-ac43-a5bcb770675e">

**Comment by dmitry-buzzwoo** [comment]
Is someone maintaining this project? Is guess not...

**Comment by abbasudo** [comment]
@dmitry-buzzwoo I have merged #9 which made the edits that you suggested. can you verify if is it working as expected now ?(get [new version](https://github.com/abbasudo/pulse-users/releases/tag/v0.6.1) by running `composer update`)

**Comment by dmitry-buzzwoo** [comment]
Thanks for the quick feedback. Yes, I can confirm that it works fine.
![Screenshot 2024-10-31 at 10 29 11](https://github.com/user-attachments/assets/3adabcf1-41c2-48e5-afa2-353752168143)

**Comment by tobya** [comment]
Thanks. Works well now.
